### ISSUE TITLE
How did you define $key and $param variables? 

### ISSUE THREAD

**Issue by changshuai80** [appolous/lazada-php-sdk#4]
I have checked your sample code, and tried to run it, but I don't understand 100% how you define $key and $param variables.
Where are these variables from?

$lazRequest->addApiParam($key, $param);

And where is $token variable from?
$response = $lazOp->execute($lazRequest, $token);

Please guide me, thanks.

**Comment by alanyeong** [comment]
The `$key` & `$param` variable, you may get from API document.
For example, [GetProducts ](https://open.lazada.com/apps/doc/api?path=%2Fproducts%2Fget) endpoint.

```
$lazRequest->addApiParam('filter', 'all');
$lazRequest->addApiParam('limit', '50');
```
Depending on your need to add or remove more API params.

For getting the access token `$token`, you can refer to [GenerateAccessToken ](https://open.lazada.com/apps/doc/api?path=%2Fauth%2Ftoken%2Fcreate) endpoint.

**Comment by changshuai80** [comment]
Ah yes yes, correct, thanks.
I realized, to get access token, I need to get code first, so I tried to open this url on my browser.

https://auth.lazada.com/oauth/authorize?response_type=code&force_auth=true&redirect_uri={redirect_url}&client_id={app_key}

So, when I open this url, it requires me to enter email and password, so I entered, but it says, "USER_NOT_EXIST" message.
![image](https://github.com/user-attachments/assets/f3833baa-5cb0-45f3-973b-a3d64cd07a04)

But I have an account and able to login to my developer account for api document.
I am not sure why.
Please guide me, thanks.

**Comment by alanyeong** [comment]
This you will required to login with **Real Seller Account**, you may try to use sandbox account with sandbox url.

**Comment by changshuai80** [comment]
Ah!!!!!!!
I see , got it.
But I am not a seller. 
Is this problem to use lazada api?

**Comment by alanyeong** [comment]
You can using the **Loan Test Account** feature. 

You may go to **App Console**. First create an app, if you haven't done so. 
After that, visit _Development >Testing Tools > Loan Test Account_ to get a testing account to proceed with your development.

**Comment by changshuai80** [comment]
Yes, I did it. I was able to use Loan Test Account, it's working fine.
But not sure what I have to do after that.

**Comment by alanyeong** [comment]
What you can try to do next is to successfully get the access token, which required the app id `app_key`, and the URL `redirect_url` to redirect back to you with the auth code. With the auth code, you can then use to generate access token. You may use any of the test account email and password to login.

`https://auth.lazada.com/oauth/authorize?response_type=code&force_auth=true&redirect_uri={redirect_url}&client_id={app_key}`

For the detail explanation, you can refer to this [article](https://open.lazada.com/apps/doc/doc?nodeId=10533&docId=108260).

All the best :)

**Comment by changshuai80** [comment]
Oh thank you so much! Great @alanyeong 
I will check the article that you shared.
Thank you again!

**Comment by changshuai80** [comment]
> This you will required to login with **Real Seller Account**, you may try to use sandbox account with sandbox url.

Sorry, I have another question.
I think, my developer account is not sandbox account but I am not sure if it's Real Seller Account because I am not a seller.
Anyway, as I mentioned above, when I try to open a url to get the code from browser, it says "USER_NOT_EXIST" message.
I created an app in my account and got an app key. It's in testing mode now.

![image](https://github.com/user-attachments/assets/399999b7-8424-4d73-9bed-8e8894ff05e0)

"USER_NOT_EXIST" message by I used app key with testing mode?
Please let me know your thoughts, thanks.

**Comment by alanyeong** [comment]
Sorry for the misinformation, I mixed up with another platform. 

On Lazada, there're only one live URL available. But the Test Account should be able to login with the provided account, maybe you check if the country selection is correct, and if the _Seller ID_ is in _Authorized Seller Whitelist_ under the app.
